[tool.poetry]
name = "templaer"
version = "0.1.0"
description = ""
authors = ["Denis <pro-progerkustov@yandex.ru>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
