version: '3.7'
services:
  web_django:
    build: ./${DJANGO_PROJ_NAME}
    volumes:
      - ./${DJANGO_PROJ_NAME}/:/code/
      - ./.env:/code/.env
    # Подсказка к каким портам будет обращение к этому контейнеру  
    expose:
      - ${DJANGO_PORT}
    # Сначало включаем БД потом nginx
    depends_on:
      - ${POSTGRES_HOST}
      - nginx

  db_postgres:
    # Берем образ postgres 
    image: postgres:alpine
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
    # Настройки для PostgreSql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    # Берем образ nginx 
    image: "nginx:alpine"
    # Проброс портов
    ports:
      - ${REAL_ENDPOINT_PORT}:${NGINX_PORT}
    volumes:
      # Перезаписываем стандартную конфигурацию nginx на нашу
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - ./${DJANGO_PROJ_NAME}/static:/www/static

